// This file is generated by Firebase Studio.
'use server';
/**
 * @fileOverview Summarizes chat data based on a user-provided prompt and a selected date range.
 *
 * - summarizeChat - A function that summarizes the chat data.
 * - SummarizeChatInput - The input type for the summarizeChat function.
 * - SummarizeChatOutput - The return type for the summarizeChat function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SummarizeChatInputSchema = z.object({
  chatData: z.string().describe('The chat data to summarize.'),
  startDate: z.string().describe('The start date for the summary.'),
  endDate: z.string().describe('The end date for the summary.'),
  prompt: z.string().describe('The prompt for the summary.'),
});
export type SummarizeChatInput = z.infer<typeof SummarizeChatInputSchema>;

const SummarizeChatOutputSchema = z.object({
  summary: z.string().describe('The summary of the chat data.'),
});
export type SummarizeChatOutput = z.infer<typeof SummarizeChatOutputSchema>;

export async function summarizeChat(input: SummarizeChatInput): Promise<SummarizeChatOutput> {
  return summarizeChatFlow(input);
}

const prompt = ai.definePrompt({
  name: 'summarizeChatPrompt',
  input: {schema: SummarizeChatInputSchema},
  output: {schema: SummarizeChatOutputSchema},
  prompt: `You are an expert chat summarizer.\nSummarize the chat data between {{startDate}} and {{endDate}} based on the following prompt:\n\nPrompt: {{prompt}}\n\nChat Data:\n{{chatData}}`,
});

const summarizeChatFlow = ai.defineFlow(
  {
    name: 'summarizeChatFlow',
    inputSchema: SummarizeChatInputSchema,
    outputSchema: SummarizeChatOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
